# Generated by Django 6.0.3 on 2026-09-17 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('regular_price', models.DecimalField(decimal_places=2, help_text='Обичайна цена', max_digits=8)),
                ('promo_price', models.DecimalField(decimal_places=2, help_text='Промоционална цена', max_digits=8)),
                ('unit_quantity', models.DecimalField(decimal_places=2, default=1, help_text='Количество, за което важи цената (напр. 1000 за 1кг, ако unit=g)', max_digits=8)),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('source_url', models.URLField(blank=True, help_text='Линк към брошурата/промоцията на магазина')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='products.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='stores.store')),
            ],
            options={
                'ordering': ['-week_start'],
                'indexes': [models.Index(fields=['week_start', 'week_end'], name='promotions__week_st_41b1ea_idx')],
            },
        ),
    ]
