# Generated by Django 6.0.3 on 2026-09-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_start', models.DateField()),
                ('total_spent', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total_regular_price', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'ordering': ['-week_start'],
            },
        ),
    ]
