# Generated by Django 6.0.3 on 2026-09-17 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('savings', '0001_initial'),
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsrecord',
            name='shopping_list',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='savings_record', to='shopping.shoppinglist'),
        ),
    ]
