# Generated by Django 6.0.3 on 2026-09-17 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('week_start', models.DateField()),
                ('note', models.TextField(blank=True, help_text='Съобщение от потребителя')),
                ('status', models.CharField(choices=[('pending', 'Чака преглед'), ('approved', 'Одобрено'), ('rejected', 'Отхвърлено')], default='pending', max_length=10)),
                ('admin_note', models.TextField(blank=True, help_text='Обратна връзка от админа')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='1-5, по желание', null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('is_approved', models.BooleanField(default=True, help_text='Модерация — скрий неподходящи коментари')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
