# Generated by Django 6.0.3 on 2026-09-17 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0001_initial'),
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menusubmission',
            name='proposed_recipes',
            field=models.ManyToManyField(blank=True, related_name='submissions', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='menusubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
