# Generated by Django 6.0.3 on 2026-09-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('mon', 'Понеделник'), ('tue', 'Вторник'), ('wed', 'Сряда'), ('thu', 'Четвъртък'), ('fri', 'Петък'), ('sat', 'Събота'), ('sun', 'Неделя')], max_length=3)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Закуска'), ('lunch', 'Обяд'), ('dinner', 'Вечеря'), ('snack', 'Междинно')], max_length=10)),
            ],
            options={
                'ordering': ['day', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Чернова'), ('pending', 'Чака одобрение'), ('approved', 'Одобрено'), ('rejected', 'Отхвърлено')], default='draft', max_length=10)),
            ],
            options={
                'ordering': ['-week_start'],
            },
        ),
    ]
