# Generated by Django 6.0.3 on 2026-09-17 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meal_plans', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklymenu',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menuentry',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='meal_plans.weeklymenu'),
        ),
    ]
