# Generated by Django 6.0.3 on 2026-09-17 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meal_plans', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Нужно количество за менюто', max_digits=8)),
                ('quantity_purchased', models.DecimalField(blank=True, decimal_places=2, help_text='Реално закупено количество. Ако е повече от нужното (напр. по-голям промо пакет), разликата автоматично отива в инвентара при финализиране на пазаруването.', max_digits=8, null=True)),
                ('estimated_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('purchased', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_start', models.DateField()),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_lists', to='meal_plans.weeklymenu')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
