# Generated by Django 6.0.3 on 2026-09-17 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStorageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_type', models.CharField(choices=[('fresh', 'Свежо / хладилник'), ('frozen', 'Замразяване'), ('canned', 'Консервиране'), ('dry', 'Сухо съхранение')], max_length=10)),
                ('shelf_life_days_when_stored', models.PositiveIntegerField(help_text='Срок на годност при това съхранение (напр. замразено)')),
                ('tips', models.TextField(blank=True, help_text='Кратки съвети за съхранение')),
            ],
        ),
        migrations.CreateModel(
            name='UserInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='В единицата на продукта', max_digits=8)),
                ('source', models.CharField(choices=[('promotion', 'Купено на промоция'), ('regular', 'Купено на редовна цена')], default='regular', max_length=10)),
                ('purchase_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'User inventories',
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('unit', models.CharField(choices=[('g', 'грам'), ('ml', 'милилитър'), ('pcs', 'брой')], default='g', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('calories_per_100', models.PositiveIntegerField(default=0)),
                ('protein_per_100', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fat_per_100', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('carbs_per_100', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('default_shelf_life_days', models.PositiveIntegerField(default=7, help_text='Типичен срок на годност при нормално съхранение (дни)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
